### ISSUE TITLE
fixed mode chat plugin has region persistently clipping

### ISSUE THREAD

**Issue by Jerrk** [deathbeam/example-plugin#12]
on the left and right side of the chat when it is hidden then two columns will retain whatever graphics is rendered on top of them.

flashing the chat on/off fixes the issue until another piece of graphics in rendered on top of it.

this is very annoying if you use the idle notification "flash" feature.

heres a small gif of the issue.
![](https://i.imgur.com/SKiqnyz.gif)

I would suggest when hiding the chat to make the left and right columns more fit to what the grasphics are inline further above.
![](https://i.imgur.com/D5TIJO8.png) ![](https://i.imgur.com/mWjLBTF.png)

thanks

**Comment by Popedigoz** [comment]
@deathbeam plz fix

**Comment by Yookiop** [comment]
Please fix this issue

**Comment by deathbeam** [comment]
Should be resolved by #36
