### ISSUE TITLE
plugin breaks when banking

### ISSUE THREAD

**Issue by Claxos** [deathbeam/example-plugin#14]
if you click too fast in the bank (by too fast i mean anything but extremely slow), you'll withdraw items from slots nowhere near the one you clicked, you'll remove placeholders, move tabs, and so on.

it's 'solved' by opening the chatbox/disabling the plugin (which just makes it more of a pain since esc to close doesn't work with the chatbox up) and i doubt many of the people using this plugin need it specifically for the bank so a simple fix would be disabling the plugin while the bank interface is open.

i do really like this plugin, so i hope the issue can be fixed

**Comment by deathbeam** [comment]
Fixed by https://github.com/deathbeam/example-plugin/pull/18
