### ISSUE TITLE
White Background bug sometimes with menus while the chat is minimized

### ISSUE THREAD

**Issue by skurptheyurp** [deathbeam/example-plugin#27]
sometimes during gameplay the entire background of the chat messes up, and leads to this

![image](https://github.com/deathbeam/example-plugin/assets/123139321/9aff74df-7241-4331-b5d4-348652e77775)

**Comment by Psicoses** [comment]
The color of the bars is the Runelite notification color. The bars appear after a full screen notification appears, and the bar's opacity seems to gradually increase until it's solid.

Disabling and re-enabling gets rid of them until the next notification.
