### ISSUE TITLE
Fixed Mode Hide Chat moves bank downwards after double-clicking or double-moving any items quickly.

### ISSUE THREAD

**Issue by wrongfifsh** [deathbeam/example-plugin#3]
![2020-12-23_07-26-12](https://user-images.githubusercontent.com/72527036/102963362-8e4ab580-44f1-11eb-883b-8bb8e8bd8562.png)

How to reproduce in fixed mode (2 ways):

1. Open bank and double-click a stack of items. The first click can be held. Might take a few tries.
2. Open bank and drag one item to the other slot, then back quickly.

You can mix both ways, but only if the item changes locations. Ex. drag and drop to a **_different_** slot and withdraw 1.

**Comment by wigglepop** [comment]
![image](https://user-images.githubusercontent.com/77034846/103878677-b81af380-5111-11eb-9094-1f6bb2f36df8.png)

reproduce this bug by changing size of your client with chat hidden or shown

**Comment by deathbeam** [comment]
Fixed in https://github.com/deathbeam/example-plugin/commit/5d4f8829d2c0c47a406b7f9aefbbda2a47f11842
