### ISSUE TITLE
Private messages are randomly going up and down sometimes

### ISSUE THREAD

**Issue by Razvanu7z** [deathbeam/example-plugin#32]
Chat cannot be hidden anymore, and as another person said a few months ago, private messages are randomly going up and down sometimes

**Comment by hectorxn** [comment]
Please somebody fix this, im too used to it now...

**Comment by LO0K0UT** [comment]
I also am experiencing this issue. I love this plugin, and although it hasn't been updated in a long time. I really hope it gets support since it is now fully broken. 

It's an awesome viewing experience for the game in fixed mode.

**Comment by deathbeam** [comment]
The main issue was solved, and rest is duplicate of https://github.com/deathbeam/example-plugin/issues/22, closing for now

**Comment by deathbeam** [comment]
https://github.com/runelite/plugin-hub/pull/5469 here is PR waiting for approvalnot fixed in release yet

**Comment by LemonAosi** [comment]
> [runelite/plugin-hub#5469](https://github.com/runelite/plugin-hub/pull/5469) here is PR waiting for approvalnot fixed in release yet

Hi, does this mean the chat issue is fixed? I had tried installing the plugin and app but still not hiding the chat box - Is there something I have to do? or do I need to wait? Thanks :)

**Comment by deathbeam** [comment]
> > [runelite/plugin-hub#5469](https://github.com/runelite/plugin-hub/pull/5469) here is PR waiting for approvalnot fixed in release yet
> 
> Hi, does this mean the chat issue is fixed? I had tried installing the plugin and app but still not hiding the chat box - Is there something I have to do? or do I need to wait? Thanks :)

It should be fixed now (like 1 min ago) so try to update the plugin or restart RL i guess
