### ISSUE TITLE
 Chatbox Sidebar Fix #36 & Fixed mode chat plugin has region persistently clipping #12 are closed, but don't work

### ISSUE THREAD

**Issue by Yookiop** [deathbeam/example-plugin#37]
the problem is still present, example in the gif below:

https://github.com/deathbeam/example-plugin/assets/157283452/d3e8afa9-71e0-4f93-9ded-cc8fa37d55c7

**Comment by deathbeam** [comment]
Yea that is because I did not made update to plugin hub yet, I will look at it soon-ish

**Comment by Yookiop** [comment]
> Yea that is because I did not made update to plugin hub yet, I will look at it soon-ish

Can you give an indication when since 2 more weeks have passed?

**Comment by Yookiop** [comment]
@deathbeam can I do the update to the plugin hub for you? I will have to look how but it's been like a month since the fix has been made by someone else, but it's not put into production
