### ISSUE TITLE
Add Compatibility/Support for Dark Mode/Resource Packs.

### ISSUE THREAD

**Issue by pkgrub** [deathbeam/example-plugin#48]
Not a real issue but as the plugin has increased in popularity and content creators use this plugin I noticed this plugin isn't compatible with Resource Packs. A dark mode option would be nice.

![fxxxxxxxxxxxx](https://github.com/user-attachments/assets/ecd908d3-26d0-4f10-94d6-7106199d91c1)

**Comment by deathbeam** [comment]
Dont really want to support other plugins and its minor issue at best so dont think it matters much anyway
