### ISSUE TITLE
Add Transparent Chatbox and Resizing Features

### ISSUE THREAD

**Issue by billy-bg** [deathbeam/example-plugin#51]
This is especially relevant with the removal of the watchdog plugin in bossing areas, making the chat being open a soft requirements at some bosses.
Not sure if the runelite API would allow for a feature like this to be implemented, but seems very similar to the transparent chatbox (chatbox opacity) and the chatbox resizing plugins that already exist (code can be merged into this plugin).
Picture attached is a rough idea of how it should look.
![how osrs should look](https://github.com/user-attachments/assets/57307b4a-8885-4d7b-b3fc-3e14f11de2b6)

**Comment by deathbeam** [comment]
Definitely out of scope of this plugin
