### ISSUE TITLE
Please Fix Fixed Mode Hide Chat Issue

### ISSUE THREAD

**Issue by SomeNoob5** [deathbeam/example-plugin#9]
The plugin used to operate similar to the resizable mode with the chat hidden, where the chat box would appear when an action needs a response, such as making potions when you need to select the amount. About a week ago it no longer functions like this and now no longer pops up when an action or dialogue requires a response. This means that you might as well turn the plugin off completely when doing tasks such as skilling because you would have to constantly reopen and close the chat box. 

I personally fell in love with this plugin for osrs because I could never decide between resizable and fixed and love the happy medium. Is this fixable? it unfortunately made this plugin no longer viable.

**Comment by superdupermaxx** [comment]
Having the same issue. I love using fixed mode hide chat but this made it basically unusable unfortunately. I hope that this can be fixed because I had to go back to using resizable and it looks so bad on stream :/

**Comment by deathbeam** [comment]
Fixed in https://github.com/deathbeam/example-plugin/commit/5d4f8829d2c0c47a406b7f9aefbbda2a47f11842
